#include <iostream>

std::string question = "What will you do?";
std::string beginning = "The year is 12,067 GE (Galactic Era). The once-mighty Galactic Empire is crumbling, and chaos threatens to engulf the galaxy. You are a member of the Psychohistorical Society, founded by the legendary Dr. Hari Seldon. Your mission is to preserve knowledge and guide humanity through the impending collapse. Stationed on the remote planet Terminus, the site of the First Foundation, you and your team are the last hope for a brighter future. As the captain of the SS Odyssey, you must navigate through perilous challenges and make critical decisions that will shape the destiny of the galaxy.";
std::string ending1 = "After decoding Dr. Seldon's message, you uncover a hidden plan to establish a Second Foundation, a secret organization dedicated to preserving knowledge and guiding humanity. The message reveals the location and purpose of the Second Foundation, ensuring that even in the darkest times, there is hope for a brighter future. Your discovery is hailed as a monumental achievement, and you are celebrated as a hero who has safeguarded the legacy of Dr. Seldon and the future of the galaxy.";
std::string ending2 = "Inside the ancient vault, you discover advanced technology from a bygone era. This technology proves to be the key to repelling the invaders threatening Terminus. With the newfound power, you lead a successful defense, driving the enemy forces away and securing the safety of the planet. The citizens of Terminus rejoice, and you are honored for your bravery and ingenuity. The advanced technology not only saves Terminus but also paves the way for a new era of scientific progress and exploration.";
std::string ending3 = "Through your diplomatic efforts, you form a strong alliance with the neighboring star system. Together, you and your new allies work to rebuild and strengthen the remnants of the Galactic Empire. This cooperation leads to a new era of peace and prosperity, as the combined forces of Terminus and the neighboring system create a stable and thriving society. Your leadership and vision are recognized as the cornerstone of this new alliance, and you are celebrated as a visionary who brought hope and unity to a fractured galaxy.";
std::string choices1 = "1. investigate the communication blackout \n 2. Focus on strengthening the defenses of Terminus.";


int main() {
    
};